language: scala
jdk:
- oraclejdk7
script:
- sbt +test +examples/test
after_success:
- ./publishViaTravis.sh
env:
  global:
  - secure: Crf4hu2G53xisZChdK0Tam/FSBX/UpbPwGi0sJq5rPSlUt3jEp/AUFnlYiKD1oWtteWHvTgdh1IRqfZfLG0G49hT9+V0knvCTAtY6tPGI+0I/L/WctINIRxMec7JdArKhwxLBJGfYN2U1XM5lGWn6ge/X+CVOFuygk8GN/+688Q=
  - secure: YPEAWead3ErfHcDohij5v7fYT9Kl6Zt5YgBtn3GVM4sKJukIJIyKXcHwxtEWvPoTYjsgFyYil9JnGZMyD+0tJ5fDf/HB6IeWuq81Tr9qn07Xh0JvuR2tWW2XhiTUt8+yJIRQ4gHH2F1UygyxTsBnaR3zSHjBoKcW72zSEQV1dEY=
  - secure: L2sXfNYgRW57FPlhEhcCkWLLT7kuq4ZvrndAxRyuoMs1Wv8IsgYGjaetktMVHIv0TAAgVBcOe8mZUjuC4VOgUcfkIblX+MHxruZcWTN5VSqGOFxm22aLymY9tM2j3XXAKa/cE/UkxDqccQtTK7SMH4+J5Iknkcv6BRu568dkOWY=
before_install:
- openssl aes-256-cbc -K $encrypted_506de5234d8d_key -iv $encrypted_506de5234d8d_iv
  -in key.private.F984A085.asc.enc -out key.private.F984A085.asc -d
- openssl aes-256-cbc -K $encrypted_506de5234d8d_key -iv $encrypted_506de5234d8d_iv
  -in key.public.F984A085.asc.enc -out key.public.F984A085.asc -d
